services:

  backend:
    build:
      context: ./sanchalan-backend
    container_name: sanchalan-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./sanchalan-abp-dashboard
    container_name: sanchalan-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
